version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-tools
    tty: true
    image: "metrics-express-tools"
    container_name: "metrics-express-tools"
    ports: 
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/app
      - node_modules:/app/node_modules 
    environment:
      NODE_ENV: "development"
volumes:
  node_modules:
